### ISSUE TITLE
InvalidPluginException on start-up

### ISSUE THREAD

**Issue by SlimeDog** [eldoriarpg/NashornJS#2]
CentOS 7.9.2009 (Core)
Java 11.0.11 2021-04-20 LTS
Spigot 1.16.5-3078
NashornJs 1.1.1

On server start-up
```
[08:58:04] [Server thread/ERROR]: Could not load 'plugins/NashornJs-1.1.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `de.eldoria.nashorn.Nashorn'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:69) ~[spigot-1.16.5-3078.jar:3078-Spigot-9fb885e-cc21bae]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-1.16.5-3078.jar:3078-Spigot-9fb885e-cc21bae]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-1.16.5-3078.jar:3078-Spigot-9fb885e-cc21bae]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-1.16.5-3078.jar:3078-Spigot-9fb885e-cc21bae]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:381) ~[spigot-1.16.5-3078.jar:3078-Spigot-9fb885e-cc21bae]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:224) ~[spigot-1.16.5-3078.jar:3078-Spigot-9fb885e-cc21bae]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928) ~[spigot-1.16.5-3078.jar:3078-Spigot-9fb885e-cc21bae]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5-3078.jar:3078-Spigot-9fb885e-cc21bae]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: de.eldoria.nashorn.Nashorn
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:138) ~[spigot-1.16.5-3078.jar:3078-Spigot-9fb885e-cc21bae]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-1.16.5-3078.jar:3078-Spigot-9fb885e-cc21bae]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[spigot-1.16.5-3078.jar:3078-Spigot-9fb885e-cc21bae]
        ... 8 more
```

**Comment by RainbowDashLabs** [comment]
Ooooooof Nice. you are my QA man toady I guess xD
Fix is on the way.

**Comment by SlimeDog** [comment]
Please make a minimal test before posting a plugin. :(

**Comment by RainbowDashLabs** [comment]
I do normally xD There are hours of testing... Should generate the main path as well automatically... Sorry for all the hastle...

Tested the build and works fine with BDO now.

**Comment by SlimeDog** [comment]
Thanks for the fast response.
