### ISSUE TITLE
Start-up failure with Java 17

### ISSUE THREAD

**Issue by SlimeDog** [eldoriarpg/NashornJS#3]
If this is a BigDoorsOpener issue please advise, and I will post there.

Versions:
```
> version
[08:44:01 INFO]: This server is running Paper version git-Paper-261 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 79e52a5)
You are running the latest version
> version NashornJs
[08:44:14 INFO]: NashornJs version 1.1.2
[08:44:14 INFO]: Nashorn JavaScript Engine for Servers on Java 15 or higher.
[08:44:14 INFO]: Authors: OpenJDK and Hadde
>version BigDoorsOpener
[08:44:53] [Server thread/INFO]: BigDoorsOpener version 2.4.4
[08:44:53] [Server thread/INFO]: Open and close doors automatically on certain conditions
[08:44:53] [Server thread/INFO]: Website: www.spigotmc.org/resources/80805/
[08:44:53] [Server thread/INFO]: Author: Hadde
```
**Problem**
NashornJS failure on server start-up, with Java 17. (Yes, it's brand new; posting for tracking purposes.)

**Expected behavior**
Clean start-up

**Stacktrace**
```
[08:35:14] [Server thread/INFO]: [BigDoorsOpener] Hooked into Big Doors successfully.
[08:35:14] [Server thread/INFO]: [BigDoorsOpener] World Guard found. Trying to get a hook.
[08:35:14] [Server thread/INFO]: [BigDoorsOpener] Hooked into world guard successfully.
[08:35:14] [Server thread/INFO]: [BigDoorsOpener] Placeholder API found. Enabling placeholder usage.
[08:35:14] [Server thread/INFO]: [BigDoorsOpener] MythicMobs not found. MythicMobs conditions are disabled.
[08:35:14] [Server thread/INFO]: [BigDoorsOpener] Config is up to date.
[08:35:14] [Server thread/INFO]: [BigDoorsOpener] Config loaded!
[08:35:14] [Server thread/INFO]: [BigDoorsOpener] Java 15 or newer detected. Searching for external Engine.
[08:35:14] [Server thread/ERROR]: [BigDoorsOpener] Plugin post start failed.
java.lang.ExceptionInInitializerError: null
        at de.eldoria.nashornjs.js.internal.runtime.Context.compile(Context.java:1509) ~[NashornJs-1.1.2.jar:?]
        at de.eldoria.nashornjs.js.internal.runtime.Context.compileScript(Context.java:1449) ~[NashornJs-1.1.2.jar:?]
        at de.eldoria.nashornjs.js.internal.runtime.Context.compileScript(Context.java:759) ~[NashornJs-1.1.2.jar:?]
        at de.eldoria.nashornjs.js.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:528) ~[NashornJs-1.1.2.jar:?]
        at de.eldoria.nashornjs.js.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:517) ~[NashornJs-1.1.2.jar:?]
        at de.eldoria.nashornjs.js.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:395) ~[NashornJs-1.1.2.jar:?]
        at de.eldoria.nashornjs.js.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:151) ~[NashornJs-1.1.2.jar:?]
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262) ~[java.scripting:?]
        at de.eldoria.bigdoorsopener.util.CachingJSEngine.<init>(CachingJSEngine.java:55) ~[BigDoorsOpener-2.4.4.jar:?]
        at de.eldoria.bigdoorsopener.core.BigDoorsOpener.onPostStart(BigDoorsOpener.java:147) ~[BigDoorsOpener-2.4.4.jar:?]
        at de.eldoria.bigdoorsopener.eldoutilities.plugin.EldoPlugin$1.run(EldoPlugin.java:220) ~[BigDoorsOpener-2.4.4.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-261]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-261]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1221) ~[patched_1.17.1.jar:git-Paper-261]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-261]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: no such method: sun.misc.Unsafe.defineAnonymousClass(Class,byte[],Object[])Class/invokeVirtual
        at de.eldoria.nashornjs.js.internal.runtime.Context$AnonymousContextCodeInstaller.lambda$getDefineAnonymousClass$0(Context.java:335) ~[NashornJs-1.1.2.jar:?]
        at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
        at de.eldoria.nashornjs.js.internal.runtime.Context$AnonymousContextCodeInstaller.getDefineAnonymousClass(Context.java:327) ~[NashornJs-1.1.2.jar:?]
        at de.eldoria.nashornjs.js.internal.runtime.Context$AnonymousContextCodeInstaller.<clinit>(Context.java:317) ~[NashornJs-1.1.2.jar:?]
        ... 16 more
Caused by: java.lang.NoSuchMethodException: no such method: sun.misc.Unsafe.defineAnonymousClass(Class,byte[],Object[])Class/invokeVirtual
        at java.lang.invoke.MemberName.makeAccessException(MemberName.java:976) ~[?:?]
        at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1117) ~[?:?]
        at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3649) ~[?:?]
        at java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:2680) ~[?:?]
        at de.eldoria.nashornjs.js.internal.runtime.Context$AnonymousContextCodeInstaller.lambda$getDefineAnonymousClass$0(Context.java:329) ~[NashornJs-1.1.2.jar:?]
        at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
        at de.eldoria.nashornjs.js.internal.runtime.Context$AnonymousContextCodeInstaller.getDefineAnonymousClass(Context.java:327) ~[NashornJs-1.1.2.jar:?]
        at de.eldoria.nashornjs.js.internal.runtime.Context$AnonymousContextCodeInstaller.<clinit>(Context.java:317) ~[NashornJs-1.1.2.jar:?]
        ... 16 more
Caused by: java.lang.NoSuchMethodError: 'java.lang.Class sun.misc.Unsafe.defineAnonymousClass(java.lang.Class, byte[], java.lang.Object[])'
        at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:?]
        at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1085) ~[?:?]
        at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1114) ~[?:?]
        at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3649) ~[?:?]
        at java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:2680) ~[?:?]
        at de.eldoria.nashornjs.js.internal.runtime.Context$AnonymousContextCodeInstaller.lambda$getDefineAnonymousClass$0(Context.java:329) ~[NashornJs-1.1.2.jar:?]
        at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
        at de.eldoria.nashornjs.js.internal.runtime.Context$AnonymousContextCodeInstaller.getDefineAnonymousClass(Context.java:327) ~[NashornJs-1.1.2.jar:?]
        at de.eldoria.nashornjs.js.internal.runtime.Context$AnonymousContextCodeInstaller.<clinit>(Context.java:317) ~[NashornJs-1.1.2.jar:?]
        ... 16 more
[08:35:14] [Server thread/ERROR]: [BigDoorsOpener] Initializing failsave mode.
```

**Comment by RainbowDashLabs** [comment]
This seems to be a bug in nashorn itself.

https://bugs.openjdk.java.net/browse/JDK-8269731
It occurred first in  JDK 17ea+23.

The solution seems just to wait until it is fixed on nashorn side. I will keep an eye on it.

**Comment by SlimeDog** [comment]
Thanks for checking. Of course, BigDoorsOpener fails as a result. :(

**Comment by RainbowDashLabs** [comment]
If you want you can just remove the nashorn engine for now. Then big doors will start again. Since it doesnt work anyway it not a real loss.

**Comment by SlimeDog** [comment]
> If you want you can just remove the nashorn engine for now. Then big doors opener will start again. Since it doesnt work anyway it not a real loss.
> BDO runs without a nashorn engine. just javascript evaluation wont work

Good point. Since we don't use JS evaluation, it's all good. Confirmed.

**Comment by SlimeDog** [comment]
It looks like updating the nashorn reference to 15.3 will do the trick.

**Comment by SlimeDog** [comment]
May we have a release, please?

**Comment by RainbowDashLabs** [comment]
Its published. I just wanted to verify it first by myself ^^
